apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.appName }}-secret"
type: Opaque
stringData:
  smtpUser: "{{ .Values.smtpUser }}"
  smtpPassword: "{{ .Values.smtpPassword }}"
  houseUrl: "{{ .Values.houseUrl }}"
  houseTruststorePath: "{{ .Values.houseTruststorePath }}"
  houseTruststorePassword: "{{ .Values.houseTruststorePassword }}"
  sslKeystorePath: "{{ .Values.sslKeystorePath }}"
  sslKeystorePassword: "{{ .Values.sslKeystorePassword }}"
  authenticationSecret: "{{ .Values.authenticationSecret }}"
  jdbcConnectionString: "{{ .Values.jdbcConnectionString }}"
  dbUser: "{{ .Values.dbUser }}"
  dbPassword: "{{ .Values.dbPassword }}"
  weatherAppId: "{{ .Values.weatherAppId }}"
