create table HOUSE_STATUS (
    ID SERIAL NOT NULL,
    TIME_UTC TIMESTAMP NOT NULL,
    TIME_LOCAL TIMESTAMP NOT NULL,
    HOUSE_TEMP DECIMAL(5,2) NOT NULL,

    PRIMARY KEY (ID)
);

create index local_time_index on HOUSE_STATUS(TIME_LOCAL);

