create table HOUSE_STATUS (
    ID INT NOT NULL AUTO_INCREMENT,
    TIME_UTC DATETIME NOT NULL,
    TIME_LOCAL DATETIME NOT NULL,
    HOUSE_TEMP DECIMAL(5,2) NOT NULL,

    PRIMARY KEY (ID),
    INDEX (TIME_LOCAL)
);

