ALTER TABLE HOUSE_STATUS
ADD COLUMN EXTERNAL_TEMP_F DECIMAL(5,2) NULL,
ADD COLUMN EXTERNAL_WIND_SPEED_MPH DECIMAL(5,2) NULL,
ADD COLUMN EXTERNAL_HUMIDITY_PERCENT DECIMAL(5,2) NULL,
ADD COLUMN EXTERNAL_PRESSURE_HPA DECIMAL(6,2) NULL;
